"""Create watchlist table

Revision ID: 1d8f73157455
Revises: b2de85baac27
Create Date: 2026-06-08 10:26:23.087838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1d8f73157455"
down_revision: Union[str, Sequence[str], None] = "b2de85baac27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "movie_id", name="uq_user_movie_watchlist"),
    )
    op.create_index(
        op.f("ix_watchlist_movie_id"), "watchlist", ["movie_id"], unique=False
    )
    op.create_index(
        op.f("ix_watchlist_user_id"), "watchlist", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watchlist_user_id"), table_name="watchlist")
    op.drop_index(op.f("ix_watchlist_movie_id"), table_name="watchlist")
    op.drop_table("watchlist")
    # ### end Alembic commands ###
